package main

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strings"

	"github.com/ikarolaborda/agent-smith/internal/config"
	"github.com/ikarolaborda/agent-smith/internal/dataset"
	"github.com/ikarolaborda/agent-smith/internal/llm"
	"github.com/ikarolaborda/agent-smith/internal/rag"
)

/*
runBuildDataset turns a folder of .md/.txt source files into an OpenAI chat
fine-tuning JSONL dataset: each file becomes one grounded Chat-SFT example
generated by the selected provider (e.g. abliteration) at low temperature. It is
the native, zero-dependency equivalent of abliteration.ai's console dataset
product, so it stays inside the offline-first single binary.
*/
func runBuildDataset(ctx context.Context, cfg *config.Config, f flags, logger *slog.Logger) error {
	if f.datasetSrc == "" {
		return errors.New("--build-dataset requires --dataset-source <dir>")
	}
	provider, err := buildProvider(ctx, cfg, f, logger)
	if err != nil {
		return fmt.Errorf("build provider: %w", err)
	}

	var items []dataset.SourceItem
	walkErr := filepath.WalkDir(f.datasetSrc, func(p string, d os.DirEntry, werr error) error {
		if werr != nil || d.IsDir() {
			return nil
		}
		ext := strings.ToLower(filepath.Ext(d.Name()))
		if ext != ".md" && ext != ".txt" {
			return nil
		}
		b, rerr := os.ReadFile(p)
		if rerr != nil {
			return nil
		}
		rel, _ := filepath.Rel(f.datasetSrc, p)
		items = append(items, dataset.SourceItem{ID: rel, Content: string(b)})
		return nil
	})
	if walkErr != nil {
		return fmt.Errorf("scan dataset source: %w", walkErr)
	}
	if len(items) == 0 {
		return fmt.Errorf("no .md/.txt source files under %s", f.datasetSrc)
	}

	logger.Info("build-dataset: generating", "items", len(items), "provider", chooseProviderName(cfg, f), "out", f.datasetOut)
	records, skipped, err := dataset.Build(ctx, provider, items, dataset.Options{})
	if err != nil {
		return fmt.Errorf("build dataset: %w", err)
	}

	out, err := os.Create(f.datasetOut)
	if err != nil {
		return fmt.Errorf("create %s: %w", f.datasetOut, err)
	}
	defer func() { _ = out.Close() }()
	if err := dataset.WriteJSONL(out, records); err != nil {
		return fmt.Errorf("write jsonl: %w", err)
	}
	logger.Info("build-dataset: done", "records", len(records), "skipped", skipped, "out", f.datasetOut)
	return nil
}

/*
runIngest is the offline path: it builds the requested embedder, opens the
RAG store, and ingests every .md under --source into --collection. The
binary exits when ingest completes.
*/
func runIngest(ctx context.Context, cfg *config.Config, f flags, logger *slog.Logger) error {
	if f.collection == "" || f.source == "" {
		return errors.New("--ingest requires --collection and --source")
	}
	embedder, err := buildSingleEmbedder(cfg, f)
	if err != nil {
		return fmt.Errorf("build embedder: %w", err)
	}
	embedders := map[string]llm.Embedder{embedder.Identity(): embedder}
	svc, err := rag.NewService(f.ragDir, embedders, logger)
	if err != nil {
		return fmt.Errorf("rag service: %w", err)
	}
	col, err := svc.Ingest(ctx, f.collection, f.source, embedder, rag.DefaultChunkOptions)
	if err != nil {
		return fmt.Errorf("ingest: %w", err)
	}
	logger.Info("ingest complete", "collection", col.Name, "chunks", len(col.Chunks), "embedder", col.EmbedderID, "dim", col.Dim)
	return nil
}
