#!/usr/bin/env python3
"""
MLX/JACCL sidecar for agent-smith's cluster control plane.

The Go process never imports MLX. It generates a hostfile from the node config,
sets the MLX environment (optionally MLX_METAL_FAST_SYNCH=1), and launches this
script, which exposes an OpenAI-compatible HTTP endpoint by wrapping
`mlx_lm.server`. Go then proxies chat requests to that loopback endpoint.

Single node:   this script runs `mlx_lm.server` directly.
Multiple nodes: this script re-launches itself under `mlx.launch --hostfile ...`
                so MLX can form a distributed group across the Thunderbolt link.
                If the distributed launcher or RDMA/ring transport is not set up,
                it fails closed. Silently placing the whole model on one host can
                overcommit unified memory and panic the kernel.

This is the first-version sidecar: it launches and proxies. The distributed
path is best-effort and fails closed when it cannot form the requested group.
See docs/cluster.md.
"""

import argparse
import json
import os
import shutil
import socket
import subprocess
import sys


def log(msg):
    print(f"[mlx_sidecar] {msg}", file=sys.stderr, flush=True)


def parse_args():
    p = argparse.ArgumentParser(description="agent-smith MLX/JACCL sidecar")
    p.add_argument("--model", required=True, help="MLX model path or HF id")
    p.add_argument("--host", default="127.0.0.1")
    p.add_argument("--port", type=int, default=8081)
    p.add_argument("--hostfile", default="", help="JSON hostfile generated by the Go control plane")
    p.add_argument("--pipeline", action="store_true", help="use pipeline parallelism instead of tensor split")
    p.add_argument("--max-tokens", type=int, default=0)
    # Internal guard: set when this process was re-launched under mlx.launch so it
    # does not try to launch itself again.
    p.add_argument("--relaunched", action="store_true", help=argparse.SUPPRESS)
    return p.parse_known_args()


def read_hosts(hostfile):
    if not hostfile or not os.path.exists(hostfile):
        return []
    try:
        with open(hostfile, "r", encoding="utf-8") as fh:
            data = json.load(fh)
        if isinstance(data, list):
            return data
    except (OSError, ValueError) as exc:
        log(f"WARNING: could not read hostfile {hostfile}: {exc}")
    return []


def check_mlx_lm():
    """Return True if mlx_lm is importable; print an actionable diagnostic if not."""
    try:
        import mlx_lm  # noqa: F401
        return True
    except ImportError:
        log("ERROR: mlx_lm is not installed in this interpreter.")
        log("Install it with:  pip install mlx-lm")
        return False


def preflight_peers(hosts, self_host):
    """Best-effort connectivity check to peer hosts; reports unreachable ones."""
    unreachable = []
    for entry in hosts:
        peer = entry.get("ssh") if isinstance(entry, dict) else str(entry)
        if not peer or peer == self_host:
            continue
        try:
            socket.getaddrinfo(peer, None)
        except socket.gaierror:
            unreachable.append(peer)
    return unreachable


def server_argv(args):
    """Argument vector for mlx_lm.server."""
    argv = ["--model", args.model, "--host", args.host, "--port", str(args.port)]
    if args.max_tokens > 0:
        argv += ["--max-tokens", str(args.max_tokens)]
    return argv


def run_server(args):
    """Exec mlx_lm.server in-process (OpenAI-compatible HTTP endpoint)."""
    if not check_mlx_lm():
        sys.exit(2)
    # Prefer the console entry point; fall back to the module form.
    if shutil.which("mlx_lm.server"):
        cmd = ["mlx_lm.server"] + server_argv(args)
    else:
        cmd = [sys.executable, "-m", "mlx_lm.server"] + server_argv(args)
    log(f"starting OpenAI endpoint: {' '.join(cmd)}")
    os.execvp(cmd[0], cmd)


def try_distributed_launch(args, hosts):
    """
    Re-launch this script under `mlx.launch --hostfile` so MLX forms a
    distributed group. Returns False (with a clear diagnostic) when the
    distributed launcher is unavailable. The caller must fail the backend;
    it must never turn a distributed placement into an unplanned single-host
    placement.
    """
    launcher = shutil.which("mlx.launch")
    if not launcher:
        log("WARNING: multi-node hostfile provided but `mlx.launch` was not found on PATH.")
        log("         Distributed MLX requires mlx + a working Thunderbolt ring/RDMA transport.")
        log("         Refusing to fall back to single-host: that could exceed the node memory budget.")
        return False

    unreachable = preflight_peers(hosts, socket.gethostname())
    if unreachable:
        log(f"WARNING: peer host(s) not resolvable: {', '.join(unreachable)}")
        log("         Check the Thunderbolt bridge / .local names and SSH reachability.")
        log("         Refusing to fall back to single-host: that could exceed the node memory budget.")
        return False

    cmd = [launcher, "--hostfile", args.hostfile, sys.executable, os.path.abspath(__file__)]
    cmd += ["--model", args.model, "--host", args.host, "--port", str(args.port), "--relaunched"]
    if args.pipeline:
        cmd += ["--pipeline"]
    if args.max_tokens > 0:
        cmd += ["--max-tokens", str(args.max_tokens)]
    log(f"launching distributed group via: {' '.join(cmd)}")
    try:
        completed = subprocess.run(cmd, check=False)
        sys.exit(completed.returncode)
    except OSError as exc:
        log(f"ERROR: mlx.launch failed to exec: {exc}; refusing unsafe single-host fallback.")
        return False


def _main():
    args, _unknown = parse_args()
    if os.environ.get("MLX_METAL_FAST_SYNCH") == "1":
        log("MLX_METAL_FAST_SYNCH=1 is set")

    hosts = read_hosts(args.hostfile)
    multi_node = len([h for h in hosts]) > 1

    if multi_node and not args.relaunched:
        if try_distributed_launch(args, hosts):
            return  # process re-exec'd; unreachable
        log("ERROR: distributed MLX launch failed; backend stopped without starting a local model.")
        sys.exit(3)

    run_server(args)


if __name__ == "__main__":
    _main()
